// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PastaApi.Models;

namespace PastaApi.Migrations
{
    [DbContext(typeof(PastaApiContext))]
    partial class PastaApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PastaApi.Models.Pasta", b =>
                {
                    b.Property<int>("PastaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("GlutenFree")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Ingredients")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NoodleType")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SauceType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Url")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PastaId");

                    b.ToTable("Pastas");

                    b.HasData(
                        new
                        {
                            PastaId = 1,
                            GlutenFree = false,
                            ImageUrl = "https://www.modernhoney.com/wp-content/uploads/2018/08/Fettuccine-Alfredo-Recipe-1.jpg",
                            Ingredients = "Pasta, tomatoes",
                            Name = "Fettucini Alfredo",
                            NoodleType = "Fettucini",
                            Origin = "Italy",
                            SauceType = "Creamy",
                            Url = "https://www.allrecipes.com/recipe/23431/to-die-for-fettuccine-alfredo/"
                        },
                        new
                        {
                            PastaId = 2,
                            GlutenFree = true,
                            ImageUrl = "www.url.com/image",
                            Ingredients = "Pasta tomatoes",
                            Name = "Cacio E Pepe",
                            NoodleType = "Dinosaur",
                            Origin = "Italy",
                            SauceType = "Tomatoey",
                            Url = "www.url.com"
                        },
                        new
                        {
                            PastaId = 3,
                            GlutenFree = false,
                            ImageUrl = "www.url.com/image",
                            Ingredients = "fettucini, tomato, basil, ground beef, parmesan",
                            Name = "Spaghetti",
                            NoodleType = "Fettucini",
                            Origin = "Italy",
                            SauceType = "Tomato Basil",
                            Url = "https://www.allrecipes.com/recipe/158140/spaghetti-sauce-with-ground-beef/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
